import wave
import os
import sys

# Change this to whatever you named your downloaded file!
MODEL_PATH = "my_cloned_voice.onnx"
OUTPUT_FILE = "test_output.wav"
TEXT = "Hello! This is my newly cloned voice running locally on my computer. I hope it sounds good!"

def test_voice():
    if not os.path.exists(MODEL_PATH):
        print(f"❌ ERROR: Cannot find '{MODEL_PATH}'!")
        print("Did you download the file from Google Drive and place it in this folder?")
        return
        
    try:
        from piper import PiperVoice
    except ImportError:
        print("❌ ERROR: The 'piper-tts' module is not installed.")
        print("Run this in your terminal: pip install piper-tts")
        return

    print(f"Loading voice model from {MODEL_PATH}...")
    try:
        voice = PiperVoice.load(MODEL_PATH)
    except Exception as e:
        print(f"ERROR loading model: {e}")
        print("Make sure you also downloaded the .json file and placed it next to the .onnx file!")
        return

    print("Synthesizing audio (this should take less than 2 seconds)...")
    
    # Generate the audio and save it to a WAV file
    with wave.open(OUTPUT_FILE, "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(voice.config.sample_rate)
        
        # Read the raw audio bytes generated by Piper and write them directly to the file
        for chunk in voice.synthesize(TEXT):
            wav_file.writeframes(chunk.audio_int16_bytes)
        
    print(f"SUCCESS! Open '{OUTPUT_FILE}' to hear your cloned voice!")

if __name__ == "__main__":
    test_voice()
